Translator1: main.o translator.o
	g++ -o Translator1 main.o translator.o

main.o: mainVer1.0.cpp
	g++ -c -o main.o mainVer1.0.cpp

translator.o: TranslatorVer1.0.cpp TranslatorVer1.0.h
	g++ -c -o translator.o TranslatorVer1.0.cpp