Translator2: main.o translator.o
	g++ -o Translator2 main.o translator.o

main.o: mainVer2.0.cpp
	g++ -c -o main.o mainVer2.0.cpp

translator.o: TranslatorVer2.0.cpp TranslatorVer2.0.h
	g++ -c -o translator.o TranslatorVer2.0.cpp